Summer2020/Summer2020/Models/ErrorViewModel.cs
using System;

namespace Summer2020.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Summer2020/Summer2020/Models/Objects.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Summer2020.Models
{
    public class Objects
    {
        public int Id { get; set; }
        // [Display(Name = "Messier Value")]
        public string Messier { get; set; }
        //[Display(Name = "Common Name")]
        public string Common { get; set; }
        //[Display(Name = "New General Catalogue Value")]
        public int NGC { get; set; }
        //[Display(Name = "Constellation")]
        public string Con { get; set; }
        //[Display(Name = "Object Type")]
        public string Type { get; set; }
        // [Display(Name = "Magnitude")]
        public float Mag { get; set; }
        //[Display(Name = "Right Ascension")]
        public int RA { get; set; }
        //[Display(Name = "Declination")]
        public int DEC { get; set; }
    }
}

Summer2020/Summer2020/Models/SeedData.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Summer2020.Data;
using System;
using System.Linq;
using System.Reflection.PortableExecutable;

namespace Summer2020.Models
{
    public static class SeedData
    {
        public static void Initialize(IServiceProvider serviceProvider)
        {
            using (var context = new Summer2020Context(
                serviceProvider.GetRequiredService<
                    DbContextOptions<Summer2020Context>>()))
            {
                if (context.Objects.Any())
                {
                    return;  
                }

                context.Objects.AddRange(
                    new Objects
                    {
                        Messier = 1,
                        Common = "s",
                        NGC = 3,
                        Con = "s",
                        Type = "x",
                        Mag = 9,
                        RA = 9,
                        DEC = 9,

                    },

                  new Objects
                  {
                      Messier = 1,
                      Common = "s",
                      NGC = 3,
                      Con = "s",
                      Type = "x",
                      Mag = 9,
                      RA = 9,
                      DEC = 9,

                  },

                  new Objects
                  {
                      Messier = 1,
                      Common = "s",
                      NGC = 3,
                      Con = "s",
                      Type = "x",
                      Mag = 9,
                      RA = 9,
                      DEC = 9,

                  },

                 new Objects
                 {
                     Messier = 1,
                     Common = "s",
                     NGC = 3,
                     Con = "s",
                     Type = "x",
                     Mag = 9,
                     RA = 9,
                     DEC = 9,

                 }
                );
                context.SaveChanges();
            }
        }
    }
}

Summer2020/Summer2020/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Summer2020.Models;

namespace Summer2020.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Summer2020/Summer2020/Controllers/ObjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Summer2020.Data;
using Summer2020.Models;

namespace Summer2020.Controllers
{
    public class ObjectsController : Controller
    {
        private readonly Summer2020Context _context;

        public ObjectsController(Summer2020Context context)
        {
            _context = context;
        }

        // GET: Objects
        public async Task<IActionResult> Index()
        {
            return View(await _context.Objects.ToListAsync());
        }

        // GET: Objects/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var objects = await _context.Objects
                .FirstOrDefaultAsync(m => m.Id == id);
            if (objects == null)
            {
                return NotFound();
            }

            return View(objects);
        }

        // GET: Objects/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Objects/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Messier,Common,NGC,Con,Type,Mag,RA,DEC")] Objects objects)
        {
            if (ModelState.IsValid)
            {
                _context.Add(objects);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(objects);
        }

        // GET: Objects/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var objects = await _context.Objects.FindAsync(id);
            if (objects == null)
            {
                return NotFound();
            }
            return View(objects);
        }

        // POST: Objects/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Messier,Common,NGC,Con,Type,Mag,RA,DEC")] Objects objects)
        {
            if (id != objects.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(objects);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ObjectsExists(objects.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(objects);
        }

        // GET: Objects/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var objects = await _context.Objects
                .FirstOrDefaultAsync(m => m.Id == id);
            if (objects == null)
            {
                return NotFound();
            }

            return View(objects);
        }

        // POST: Objects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var objects = await _context.Objects.FindAsync(id);
            _context.Objects.Remove(objects);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ObjectsExists(int id)
        {
            return _context.Objects.Any(e => e.Id == id);
        }
    }
}

Summer2020/Summer2020/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Summer2020/Summer2020/Views/Objects/Create.cshtml
@model Summer2020.Models.Objects

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Objects</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Messier" class="control-label"></label>
                <input asp-for="Messier" class="form-control" />
                <span asp-validation-for="Messier" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Common" class="control-label"></label>
                <input asp-for="Common" class="form-control" />
                <span asp-validation-for="Common" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NGC" class="control-label"></label>
                <input asp-for="NGC" class="form-control" />
                <span asp-validation-for="NGC" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Con" class="control-label"></label>
                <input asp-for="Con" class="form-control" />
                <span asp-validation-for="Con" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mag" class="control-label"></label>
                <input asp-for="Mag" class="form-control" />
                <span asp-validation-for="Mag" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RA" class="control-label"></label>
                <input asp-for="RA" class="form-control" />
                <span asp-validation-for="RA" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DEC" class="control-label"></label>
                <input asp-for="DEC" class="form-control" />
                <span asp-validation-for="DEC" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Summer2020/Summer2020/Views/Objects/Delete.cshtml
@model Summer2020.Models.Objects

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Objects</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Messier)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Messier)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Common)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Common)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NGC)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NGC)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Con)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Con)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Mag)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Mag)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RA)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RA)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DEC)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DEC)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Summer2020/Summer2020/Views/Objects/Details.cshtml
@model Summer2020.Models.Objects

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Objects</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Messier)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Messier)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Common)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Common)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NGC)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NGC)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Con)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Con)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Mag)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Mag)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RA)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RA)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DEC)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DEC)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Summer2020/Summer2020/Views/Objects/Edit.cshtml
@model Summer2020.Models.Objects

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Objects</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Messier" class="control-label"></label>
                <input asp-for="Messier" class="form-control" />
                <span asp-validation-for="Messier" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Common" class="control-label"></label>
                <input asp-for="Common" class="form-control" />
                <span asp-validation-for="Common" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NGC" class="control-label"></label>
                <input asp-for="NGC" class="form-control" />
                <span asp-validation-for="NGC" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Con" class="control-label"></label>
                <input asp-for="Con" class="form-control" />
                <span asp-validation-for="Con" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mag" class="control-label"></label>
                <input asp-for="Mag" class="form-control" />
                <span asp-validation-for="Mag" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RA" class="control-label"></label>
                <input asp-for="RA" class="form-control" />
                <span asp-validation-for="RA" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DEC" class="control-label"></label>
                <input asp-for="DEC" class="form-control" />
                <span asp-validation-for="DEC" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Summer2020/Summer2020/Views/Objects/Index.cshtml
@model IEnumerable<Summer2020.Models.Objects>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Messier)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Mesier)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Common)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NGC)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Con)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Mag)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RA)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DEC)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Messier)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Mesier)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Common)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NGC)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Con)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Mag)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RA)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DEC)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Summer2020/Summer2020/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Summer 2020</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Objects" asp-action="Index">Summer 2020</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Summer 2020 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>